# Generated by Django 5.2.1 on 2025-06-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_jenis_barang_waktu_post_barang_jenis_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='jenis_id',
            new_name='jenis',
        ),
    ]
