# Generated by Django 5.2.1 on 2025-06-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_rename_jenis_id_barang_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='portofolio/')),
                ('link_sumber', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
