# Generated by Django 5.2.1 on 2025-07-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='subjudul',
            field=models.CharField(default='Subjudul', max_length=100),
        ),
    ]
