# Generated by Django 5.2.1 on 2025-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_hero_subjudul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
